FROM ubuntu:latest
MAINTAINER Kimihiko NAKAMURA nakamura.808@gmail.com

RUN apt-get update \
    && apt-get -y install software-properties-common \
    && add-apt-repository -y ppa:groonga/ppa \
    && apt-get update \
    && apt-get -y install groonga

RUN mkdir /var/lib/groonga

EXPOSE 10041
ENTRYPOINT ["groonga"]
